### ISSUE TITLE
LEAF for Multi-class

### ISSUE THREAD

**Issue by singsinghai** [amparore/leaf#5]
Hi @amparore ,
I have found a way to make LEAF work for multiclass by just fixing 2 lines of code
```
label_x0 = np.argmax(output) # To get the index of the output with highest probability
``` 
 in ```LEAF.explain_instance()```
and 
```
features_weights = [x[1] for x in lime_expl.local_exp[label_x0]] # Fix from .as_list() to .local_exp because LIME is reported to have bugs in .as_list() function when working with multiclass
```
 in ```get_LIME_classifier```.

I am currently working on how to make LEAF work for regression as well.
Would you mind if I contribute this as a merge request to your repo?

**Comment by amparore** [comment]
very good. I do not see problems with both changes.
yes, you can send a pull request to the repository.

**Comment by singsinghai** [comment]
Yes, I have just created a pull request here https://github.com/amparore/leaf/pull/6, please have a review on it.
Thanks!
